apiVersion: v1
kind: Secret
metadata:
  name: happy-kitchen-secrets
  namespace: happy-kitchen
type: Opaque
data:
  DB_HOST: BASE64_ENCODED_VALUE       
  DB_USER: BASE64_ENCODED_VALUE
  DB_PASS: BASE64_ENCODED_VALUE
  DB_NAME: BASE64_ENCODED_VALUE
  DB_PORT: BASE64_ENCODED_VALUE       
  SECRET_KEY: BASE64_ENCODED_VALUE