apiVersion: v1
kind: Service
metadata:
  name: happy-kitchen-api
  namespace: happy-kitchen
spec:
  type: NodePort
  selector:
    app: happy-kitchen-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080